### PR TITLE
feat: use node api

### PR DESCRIPTION
**Pull request by sto3psl**
Corresponding change to https://github.com/datawrapper/datawrapper/pull/267.

Is there a better way to access the API domain?

### CODE REVIEW

**Comment by gka** [comment]
> Is there a better way to access the API domain?

currently not.

**Comment by gka** [comment]
is it intentional that we use `PUT` here but `PATCH` in the datawrapper/datawrapper repo?

**Comment by sto3psl** [comment]
> is it intentional that we use PUT here but PATCH in the datawrapper/datawrapper repo?
Nope. That's my bad.

**Comment by davidkokkelink** [comment]
also, you can get rid of `chart.get().mode === 'print' ? '?mode=print' : ''` since it's not implemented in the new API

**Comment by sto3psl** [comment]
> also, you can get rid of chart.get().mode === 'print' ? '?mode=print' : '' since it's not implemented in the new API

Is that something that is needed in the new API?

**Comment by davidkokkelink** [comment]
this feature is set to be revisited once the chart editor is fully sveltified, until then we need to have _something_ for production usage, but we don't necessarily need to implement it in the new API. one solution could be to simply send requests to the old api if `mode == 'print'`.

**Pull request merged**
